### ISSUE TITLE
Terraform Integration

### ISSUE THREAD

**Issue by houst0n** [joernott/go-proxmox#1]
Hi mate,

I was looking at using this to create a terraform provider for proxmox; was this your intended use of the library? 

It looks like I'll need to make a bunch of changes to get it to work in a similar fashion to how most of the other providers work -- let me know if you'd want my changes or if I'm better starting another project :)

Cheers!

H

**Comment by joernott** [comment]
Hello houst0n,

I wrote this library as part of writing a command line tool to manage a ProxMox/Foreman cluster in an automated build system. As a sysadmin starting out with Go, I am more than happy to accept all extensions/improvements/standardisations and any advice from others to make this library better.

As long as people agree to the open license of the project, I'll encourage them to join me on this project.

**Comment by mrjcleaver** [comment]
https://github.com/lord2800/terraform-provider-proxmox/issues/1
